# .PHONY

clean:
	rm *.class
	
# Build JAVA
HelloWorld.class : HelloWorld.java
	javac HelloWorld.java


run-java : HelloWorld.class
	java HelloWorld

# Run Pyhon 
run-python : 
	python hello-world.py

# Run node
run-node :
	node hello-world.js
